### ISSUE TITLE
Error when using CRA and Jest

### ISSUE THREAD

**Issue by Fer0x** [Dipen-Dedania/mr-emoji#2]
Here error, which I got with built create-react-app test:

```js
 FAIL  src/components/App.test.js
  ● Test suite failed to run

    Cannot find module 'mr-emoji' from 'App.js'
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:179:17)
      at Object.<anonymous> (src/components/App.js:2:16)
```

It seems like something wrong with `package.json`, that jest can't resolve module.
Besides, my IDE -  WebStorm also says that module is not installed.

**Comment by cesarlima-hotmart** [comment]
Same problem here.
